const fallbackAnimeSeries = [
  {
    // === Dragon Ball Series ===
    id: 236994,
    name: "Dragon Ball DAIMA",
    original_name: "ドラゴンボールDAIMA",
    overview: "Mysteriously transformed into mini versions of themselves, Goku and his friends travel to the Demon Realm to uncover the truth and find a cure.",
    poster_path: "/8tpLyWAmYhe1D0d62gV3CWFDu2f.jpg",
    backdrop_path: "/oUmWLyeko3kYdUr8DBLIsxwcugl.jpg",
    vote_average: 8.2,
    vote_count: 504,
    first_air_date: "2024-10-11",
    genre_ids: [16, 10759, 35, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 42.7039,
    adult: false,
  },
  {
    id: 12971,
    name: "Dragon Ball Z",
    original_name: "ドラゴンボールゼット",
    overview: "Now happily married and with a son, martial arts champion Goku must defend Earth from a series of extraterrestrial invaders bent on destruction.",
    poster_path: "/i1lMlxir5E4jyeLlqS2bK1Cn3Tt.jpg",
    backdrop_path: "/ydf1CeiBLfdxiyNTpskM0802TKl.jpg",
    vote_average: 8.3,
    vote_count: 4621,
    first_air_date: "1989-04-26",
    genre_ids: [16, 10765, 10759],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 228.5688,
    adult: false,
  },
  {
    id: 12609,
    name: "Dragon Ball",
    original_name: "ドラゴンボール",
    overview: "Young Goku sets off on a quest with his teenage friend Bulma to find the seven Dragon Balls, which grant whoever possesses them a single wish.",
    poster_path: "/onCLyCOgszTIyyVs2XKYSkKPOPG.jpg",
    backdrop_path: "/30L49n4Dhn7dzuGG50GV3ybMhC3.jpg",
    vote_average: 8.3,
    vote_count: 3211,
    first_air_date: "1986-02-26",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 2.3329,
    adult: false,
  },
  {
    id: 62715,
    name: "Dragon Ball Super",
    original_name: "ドラゴンボール超（スーパー）",
    overview: "With Majin Buu defeated half-a-year prior, peace returns to Earth, where Son Goku (now a radish farmer) and his friends now live peaceful lives. However, a new threat appears in the form of Beerus, the God of Destruction...",
    poster_path: "/qEUrbXJ2qt4Rg84Btlx4STOhgte.jpg",
    backdrop_path: "/qA2UwUQbj05aeBMCuC0mHSQ4loE.jpg",
    vote_average: 8.2,
    vote_count: 5081,
    first_air_date: "2015-07-05",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 54.3902,
    adult: false,
  },
  {
    id: 12697,
    name: "Dragon Ball GT",
    original_name: "ドラゴンボールGT",
    overview: "Ten years have passed since Goku left his friends and family to hone his skills. But Goku soon finds himself helpless against the mystical power of the Dragon Balls and an accidental wish made by the devious Emperor Pilaf...",
    poster_path: "/rLHhDpv6rrhuzBjNzaMRNv2fng.jpg",
    backdrop_path: "/aJOlYXjxb5IvnTsO4I1tmFpC7GH.jpg",
    vote_average: 7.681,
    vote_count: 1976,
    first_air_date: "1996-02-07",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 5.0595,
    adult: false,
  },
  {
    id: 80020,
    name: "Super Dragon Ball Heroes",
    original_name: "スーパードラゴンボールヒーローズ",
    overview: "Trunks returns from the future to train with Goku and Vegeta. However, it disappears without warning. Then the mysterious Fu bursts in...",
    poster_path: "/8jq6xv5c1WK7KAPOXCsodm8eUxp.jpg",
    backdrop_path: "/xlKKD1TXJvh0YYlVPqqQ3g3ZUjM.jpg",
    vote_average: 7.568,
    vote_count: 3081,
    first_air_date: "2018-07-01",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 23.4938,
    adult: false,
  },
  // === Dragon Ball Series ===
  // (Already added above...)

  // === One Piece ===
  {
    id: 37854,
    name: "One Piece",
    original_name: "ワンピース",
    overview: "Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous \"One Piece\" behind...",
    poster_path: "/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg",
    backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
    vote_average: 8.723,
    vote_count: 4943,
    first_air_date: "1999-10-20",
    genre_ids: [10759, 35, 16],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 92.8187,
    adult: false,
  },

  // === Naruto ===
  {
    id: 46260,
    name: "Naruto",
    original_name: "ナルト",
    overview: "Naruto Uzumaki, a mischievous adolescent ninja, searches for recognition and dreams of becoming the Hokage.",
    poster_path: "/xppeysfvDKVx775MFuH8Z9BlpMk.jpg",
    backdrop_path: "/xuJ0F9RfKvVSJNDg2usurQ9WvY5.jpg",
    vote_average: 8.4,
    vote_count: 5732,
    first_air_date: "2002-10-03",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 95.2448,
    adult: false,
  },

  {
    id: 31910,
    name: "Naruto Shippūden",
    original_name: "ナルト 疾風伝",
    overview: "After 2 and a half years Naruto finally returns to Konoha and faces new threats like the Akatsuki.",
    poster_path: "/71mASgFgSiPl9QUexVH8BubU0lD.jpg",
    backdrop_path: "/nAeS7F2B22XQOLh5HVNXn8G3ZRk.jpg",
    vote_average: 8.534,
    vote_count: 8378,
    first_air_date: "2007-02-15",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 34.8529,
    adult: false,
  },

  {
    id: 70881,
    name: "Boruto: Naruto Next Generations",
    original_name: "BORUTO-ボルト- NARUTO NEXT GENERATIONS",
    overview: "Boruto Uzumaki enrolls in the Ninja Academy as mysterious events unfold in his world.",
    poster_path: "/e0B6i48kxdRkMcK4tR4YNfXGWOc.jpg",
    backdrop_path: "/4jDRuUk02VGAVMBJXabI9r0Cj6j.jpg",
    vote_average: 7.851,
    vote_count: 2443,
    first_air_date: "2017-04-05",
    genre_ids: [16, 10751, 10759, 35],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 7.4426,
    adult: false,
  },

  // === Pokémon ===
  {
    id: 60572,
    name: "Pokémon",
    original_name: "ポケットモンスター",
    overview: "Join Ash and Pikachu as they travel through many regions, meet friends, and pursue Ash’s dream of becoming a Pokémon Master.",
    poster_path: "/rOuGm07PxBhEsK9TaGPRQVJQm1X.jpg",
    backdrop_path: "/yYpQV25I7XB6S0POJOScPjxYWV5.jpg",
    vote_average: 7.9,
    vote_count: 1991,
    first_air_date: "1997-04-01",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 245.0467,
    adult: false,
  },

  {
    id: 220150,
    name: "Pokémon Horizons",
    original_name: "ポケットモンスター",
    overview: "Liko and Roy unravel mysteries while traveling with Captain Pikachu and others on an exciting Pokémon adventure.",
    poster_path: "/amemXW39lMbNBJFRMJ5W7q9mLP2.jpg",
    backdrop_path: "/d0axpGojOqDag5lDa0eNSEtw11l.jpg",
    vote_average: 9.0,
    vote_count: 85,
    first_air_date: "2023-04-14",
    genre_ids: [10765, 10759, 10762, 35, 16],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 81.3247,
    adult: false,
  },

  {
    id: 207567,
    name: "Pokémon: The Arceus Chronicles",
    original_name: "ポケットモンスター 神とよばれし アルセウス",
    overview: "Ash, Goh and Dawn uncover a Team Galactic plot while investigating the mythical Pokémon Arceus.",
    poster_path: "/wfToCZbH3pCLzAqIKu0RBL3v1ek.jpg",
    backdrop_path: "/5X77Ep0wZLuxVuDhh5g7xJr3R9d.jpg",
    vote_average: 7.3,
    vote_count: 36,
    first_air_date: "2022-01-21",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 17.7145,
    adult: false,
  },
];
// in the fallbackAnimeSeries i added dragoball, one piece, naruto, poekomon, 
// I WILL ADD ONE OUNCH MAN TY GI OH ATTACK ON TITAN AND SOME MORE 