export const JP_fallbackAnimeSeries = [
    // === Dragon Ball Series ===
    {
      id: 12609,
      name: "Dragon Ball",
      original_name: "ドラゴンボール",
      overview: "Young Goku sets off on a quest with his teenage friend Bulma to find the seven Dragon Balls, which grant whoever possesses them a single wish.",
      poster_path: "/onCLyCOgszTIyyVs2XKYSkKPOPG.jpg",
      backdrop_path: "/30L49n4Dhn7dzuGG50GV3ybMhC3.jpg",
      vote_average: 8.3,
      vote_count: 3211,
      first_air_date: "1986-02-26",
      genre_ids: [16, 10759, 10765],
      origin_country: ["JP"],
      original_language: "ja",
      popularity: 2.3329,
      adult: false,
    },
  {
    id: 12971,
    name: "Dragon Ball Z",
    original_name: "ドラゴンボールゼット",
    overview: "Now happily married and with a son, martial arts champion Goku must defend Earth from a series of extraterrestrial invaders bent on destruction.",
    poster_path: "/i1lMlxir5E4jyeLlqS2bK1Cn3Tt.jpg",
    backdrop_path: "/ydf1CeiBLfdxiyNTpskM0802TKl.jpg",
    vote_average: 8.3,
    vote_count: 4621,
    first_air_date: "1989-04-26",
    genre_ids: [16, 10765, 10759],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 228.5688,
    adult: false,
  },
  {
    id: 37854,
    name: "One Piece",
    original_name: "ワンピース",
    overview: "Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous \"One Piece\" behind...",
    poster_path: "/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg",
    backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
    vote_average: 8.723,
    vote_count: 4943,
    first_air_date: "1999-10-20",
    genre_ids: [10759, 35, 16],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 92.8187,
    adult: false,
  },

  // === Naruto ===
  {
    id: 46260,
    name: "Naruto",
    original_name: "ナルト",
    overview: "Naruto Uzumaki, a mischievous adolescent ninja, searches for recognition and dreams of becoming the Hokage.",
    poster_path: "/xppeysfvDKVx775MFuH8Z9BlpMk.jpg",
    backdrop_path: "/xuJ0F9RfKvVSJNDg2usurQ9WvY5.jpg",
    vote_average: 8.4,
    vote_count: 5732,
    first_air_date: "2002-10-03",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 95.2448,
    adult: false,
  },
  {
    id: 60572,
    name: "Pokémon",
    original_name: "ポケットモンスター",
    overview: "Join Ash and Pikachu as they travel through many regions, meet friends, and pursue Ash’s dream of becoming a Pokémon Master.",
    poster_path: "/rOuGm07PxBhEsK9TaGPRQVJQm1X.jpg",
    backdrop_path: "/yYpQV25I7XB6S0POJOScPjxYWV5.jpg",
    vote_average: 7.9,
    vote_count: 1991,
    first_air_date: "1997-04-01",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 245.0467,
    adult: false,
  },
  {
    id: 63926,
    name: "One-Punch Man",
    original_name: "ワンパンマン",
    overview: "Saitama is a hero who only became a hero for fun...",
    poster_path: "/jbYJuxfZMpYDalkiOnBcCv9TaL.jpg",
    backdrop_path: "/3AXLSxMuqyZt8HyrKKfrcJtkswD.jpg",
    vote_average: 8.401,
    vote_count: 3765,
    first_air_date: "2015-10-05",
    genre_ids: [16, 35, 10759],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 46.5562,
    adult: false,
  },
  {
    id: 1429,
    name: "Attack on Titan",
    original_name: "進撃の巨人",
    overview: "Many years ago, the last remnants of humanity were forced to retreat behind the towering walls...",
    poster_path: "/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    backdrop_path: "/aok7IhrbA83josNz9Dqh8tNA0Ao.jpg",
    vote_average: 8.668,
    vote_count: 6866,
    first_air_date: "2013-04-07",
    genre_ids: [16, 10765, 10759],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 45.3767,
    adult: false,
  },
  {
    id: 902,
    name: "Yu-Gi-Oh! Duel Monsters",
    original_name: "遊☆戯☆王デュエルモンスターズ",
    overview: "Bullies often target someone frail and weak—someone exactly like Yûgi Muto...",
    poster_path: "/ra8CKkCHjSok8L9meEP4WuOukNK.jpg",
    backdrop_path: "/gJYZBM200Flldo6im3EEdXslR1j.jpg",
    vote_average: 8.245,
    vote_count: 974,
    first_air_date: "2000-04-18",
    genre_ids: [16, 10759],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 15.5816,
    adult: false,
  },
  // {   Bad quality Image
  //   id: 62715,
  //   name: "Dragon Ball Super",
  //   original_name: "ドラゴンボール超（スーパー）",
  //   overview: "With Majin Buu defeated half-a-year prior, peace returns to Earth, where Son Goku (now a radish farmer) and his friends now live peaceful lives. However, a new threat appears in the form of Beerus, the God of Destruction...",
  //   poster_path: "/qEUrbXJ2qt4Rg84Btlx4STOhgte.jpg",
  //   backdrop_path: "/qA2UwUQbj05aeBMCuC0mHSQ4loE.jpg",
  //   vote_average: 8.2,
  //   vote_count: 5081,
  //   first_air_date: "2015-07-05",
  //   genre_ids: [16, 10759, 10765],
  //   origin_country: ["JP"],
  //   original_language: "ja",
  //   popularity: 54.3902,
  //   adult: false,
  // },
  // {          Bad quality Image
  //   id: 12697,
  //   name: "Dragon Ball GT",
  //   original_name: "ドラゴンボールGT",
  //   overview: "Ten years have passed since Goku left his friends and family to hone his skills. But Goku soon finds himself helpless against the mystical power of the Dragon Balls and an accidental wish made by the devious Emperor Pilaf...",
  //   poster_path: "/rLHhDpv6rrhuzBjNzaMRNv2fng.jpg",
  //   backdrop_path: "/aJOlYXjxb5IvnTsO4I1tmFpC7GH.jpg",
  //   vote_average: 7.681,
  //   vote_count: 1976,
  //   first_air_date: "1996-02-07",
  //   genre_ids: [16, 10759, 10765],
  //   origin_country: ["JP"],
  //   original_language: "ja",
  //   popularity: 5.0595,
  //   adult: false,
  // },
  {
    id: 236994,
    name: "Dragon Ball DAIMA",
    original_name: "ドラゴンボールDAIMA",
    overview: "Mysteriously transformed into mini versions of themselves, Goku and his friends travel to the Demon Realm to uncover the truth and find a cure.",
    poster_path: "/8tpLyWAmYhe1D0d62gV3CWFDu2f.jpg",
    backdrop_path: "/oUmWLyeko3kYdUr8DBLIsxwcugl.jpg",
    vote_average: 8.2,
    vote_count: 504,
    first_air_date: "2024-10-11",
    genre_ids: [16, 10759, 35, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 42.7039,
    adult: false,
  },
  // === Dragon Ball Series ===
  // (Already added above...)

  // === One Piece ===
 
  {
    id: 31910,
    name: "Naruto Shippūden",
    original_name: "ナルト 疾風伝",
    overview: "After 2 and a half years Naruto finally returns to Konoha and faces new threats like the Akatsuki.",
    poster_path: "/71mASgFgSiPl9QUexVH8BubU0lD.jpg",
    backdrop_path: "/nAeS7F2B22XQOLh5HVNXn8G3ZRk.jpg",
    vote_average: 8.534,
    vote_count: 8378,
    first_air_date: "2007-02-15",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 34.8529,
    adult: false,
  },
  {
    id: 70881,
    name: "Boruto: Naruto Next Generations",
    original_name: "BORUTO-ボルト- NARUTO NEXT GENERATIONS",
    overview: "Boruto Uzumaki enrolls in the Ninja Academy as mysterious events unfold in his world.",
    poster_path: "/e0B6i48kxdRkMcK4tR4YNfXGWOc.jpg",
    backdrop_path: "/4jDRuUk02VGAVMBJXabI9r0Cj6j.jpg",
    vote_average: 7.851,
    vote_count: 2443,
    first_air_date: "2017-04-05",
    genre_ids: [16, 10751, 10759, 35],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 7.4426,
    adult: false,
  },

  // === Pokémon ===
  

  {
    id: 220150,
    name: "Pokémon Horizons",
    original_name: "ポケットモンスター",
    overview: "Liko and Roy unravel mysteries while traveling with Captain Pikachu and others on an exciting Pokémon adventure.",
    poster_path: "/amemXW39lMbNBJFRMJ5W7q9mLP2.jpg",
    backdrop_path: "/d0axpGojOqDag5lDa0eNSEtw11l.jpg",
    vote_average: 9.0,
    vote_count: 85,
    first_air_date: "2023-04-14",
    genre_ids: [10765, 10759, 10762, 35, 16],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 81.3247,
    adult: false,
  },

  {
    id: 207567,
    name: "Pokémon: The Arceus Chronicles",
    original_name: "ポケットモンスター 神とよばれし アルセウス",
    overview: "Ash, Goh and Dawn uncover a Team Galactic plot while investigating the mythical Pokémon Arceus.",
    poster_path: "/wfToCZbH3pCLzAqIKu0RBL3v1ek.jpg",
    backdrop_path: "/5X77Ep0wZLuxVuDhh5g7xJr3R9d.jpg",
    vote_average: 7.3,
    vote_count: 36,
    first_air_date: "2022-01-21",
    genre_ids: [16, 10759, 10765],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 17.7145,
    adult: false,
  },
  
  
  {
    id: 12536,
    name: "Yu-Gi-Oh! GX",
    original_name: "遊戯王デュエルモンスターズＧＸ",
    overview: "Ten years after the Ceremonial Battle, a teenage boy named Judai Yuuki heads off to Duel Academia...",
    poster_path: "/vhY30rXaM5axSpAdr1M1HRQrQGa.jpg",
    backdrop_path: "/thC21OmJxXR0FoUrkEk644rRO2M.jpg",
    vote_average: 7.926,
    vote_count: 284,
    first_air_date: "2004-10-06",
    genre_ids: [16, 10762, 35, 10759],
    origin_country: ["JP"],
    original_language: "ja",
    popularity: 92.505,
    adult: false,
  },
  // { Bad quality Image
  //   id: 13916,
  //   name: "Death Note",
  //   original_name: "DEATH NOTE",
  //   overview: "Light Yagami is an ace student with great prospects—and he’s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god. Any human whose name is written in the notebook dies, and Light has vowed to use the power of the Death Note to rid the world of evil. But will Light succeed in his noble goal, or will the Death Note turn him into the very thing he fights against?",
  //   poster_path: "/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg",
  //   backdrop_path: "/koBa94NxTaGe2FoDzlXMuJptsv0.jpg",
  //   vote_average: 8.632,
  //   vote_count: 4445,
  //   first_air_date: "2006-10-04",
  //   genre_ids: [16, 9648, 10765],
  //   origin_country: ["JP"],
  //   original_language: "ja",
  //   popularity: 50.0531,
  //   adult: false,
  // }
];

export const US_fallbackAnimeSeries = [
  {
    id: 2660,
    name: "Codename: Kids Next Door",
    original_name: "Codename: Kids Next Door",
    overview: "Taking numbers instead of names, five extraordinary 10-year-olds form a covert team called the Kids Next Door with one dedicated mission: to free all children from the tyrannical rule of adults.",
    poster_path: "/ppM8Pl6e8JIr39HPLRFgqDH3Vf1.jpg",
    backdrop_path: "/h7rHu5pt9Wzkb7vLGKrA5XD63ge.jpg",
    vote_average: 8.2,
    vote_count: 744,
    first_air_date: "2002-12-06",
    genre_ids: [16, 10759, 35, 10765, 10762, 10751],
    origin_country: ["US"],
    original_language: "en",
    popularity: 1.6589,
    adult: false,
  },
  {
    id: 2405,
    name: "Johnny Bravo",
    original_name: "Johnny Bravo",
    overview: "Johnny Bravo tells the story of a biceps-bulging, karate-chopping free spirit who believes he is a gift from God to the women of the earth...",
    poster_path: "/obbdeoOk8XSXzJrWGiBbaeMMSMl.jpg",
    backdrop_path: "/vv2FQBvol6JgL9AO8mwi8jaoaNv.jpg",
    vote_average: 7.298,
    vote_count: 595,
    first_air_date: "1997-07-07",
    genre_ids: [16, 35, 10751],
    origin_country: ["US"],
    original_language: "en",
    popularity: 80.1483,
    adult: false,
  },
  {
    id: 472,
    name: "Megas XLR",
    original_name: "Megas XLR",
    overview: "Megas XLR is a series about an overweight couch potato named Coop who stumbles across a giant robot in a junkyard...",
    poster_path: "/d4Mc687WE8wFAk5nlmJJh4qNuIO.jpg",
    backdrop_path: "/vhDErhLUBnyLdDNtgaeOYAfIoM2.jpg",
    vote_average: 8.198,
    vote_count: 96,
    first_air_date: "2004-05-01",
    genre_ids: [16, 10759, 35, 10765, 10762],
    origin_country: ["US"],
    original_language: "en",
    popularity: 9.8166,
    adult: false,
  },
  {
    id: 2723,
    name: "Samurai Jack",
    original_name: "Samurai Jack",
    overview: "A great warrior is displaced to the distant future by the evil shape-shifting wizard Aku...",
    poster_path: "/ddZ7Q2WZ0xAHkVXYvcEgNGFgVkw.jpg",
    backdrop_path: "/CrVAqxtdmvelqVcj8pVeQg7wNV.jpg",
    vote_average: 8.448,
    vote_count: 824,
    first_air_date: "2001-08-10",
    genre_ids: [10765, 10759, 16],
    origin_country: ["US"],
    original_language: "en",
    popularity: 44.0939,
    adult: false,
  },
  {
    id: 2328,
    name: "Power Rangers",
    original_name: "Power Rangers",
    overview: "A team of teenagers with attitude are recruited to save Angel Grove from the evil witch, Rita Repulsa...",
    poster_path: "/qx3SJlAp2RK656TusqKx1qEqVMW.jpg",
    backdrop_path: "/i01wnWz0Z3rMATqbkAVLHEaGbNP.jpg",
    vote_average: 7.076,
    vote_count: 794,
    first_air_date: "1993-08-28",
    genre_ids: [10759, 10765, 10762],
    origin_country: ["US"],
    original_language: "en",
    popularity: 33.4547,
    adult: false,
  },
  {
    id: 606,
    name: "Ed, Edd n Eddy",
    original_name: "Ed, Edd n Eddy",
    overview: "Three adolescent boys, Ed, Edd \"Double D\", and Eddy, constantly invent schemes to make money from their peers...",
    poster_path: "/nfKenwmfmdtoXGhaYiDIftrBchw.jpg",
    backdrop_path: "/f307veKEFZqvFRkMkffDEXf280w.jpg",
    vote_average: 7.9,
    vote_count: 757,
    first_air_date: "1999-01-04",
    genre_ids: [16, 35, 10762, 10751],
    origin_country: ["CA", "US"],
    original_language: "en",
    popularity: 28.0792,
    adult: false,
  },
  {
    id: 897,
    name: "The Grim Adventures of Billy and Mandy",
    original_name: "The Grim Adventures of Billy and Mandy",
    overview: "The exploits of the Grim Reaper, who has been forced into being the best friend of two children...",
    poster_path: "/kbFIKt6NGppNr7OOn288A8gBObs.jpg",
    backdrop_path: "/1eRvnxCQLrMjCieyO8VBsPJ28Jv.jpg",
    vote_average: 8.1,
    vote_count: 981,
    first_air_date: "2001-08-24",
    genre_ids: [16, 10751, 10765, 35, 10762],
    origin_country: ["US"],
    original_language: "en",
    popularity: 46.6103,
    adult: false,
  },
  {
    id: 2085,
    name: "Courage the Cowardly Dog",
    original_name: "Courage the Cowardly Dog",
    overview: "The bizarre misadventures of a cowardly dog named Courage and his elderly owners in a farmhouse in Nowhere, Kansas.",
    poster_path: "/dzD8EWDvtg7rBCINu0RCH5EUejh.jpg",
    backdrop_path: "/cFuk3BU0sid8dby05eyyBPtK4dD.jpg",
    vote_average: 8.2,
    vote_count: 1557,
    first_air_date: "1999-11-12",
    genre_ids: [16, 10751, 10765, 35, 10762],
    origin_country: ["US"],
    original_language: "en",
    popularity: 46.7771,
    adult: false,
  },
  {
    id: 4229,
    name: "Dexter's Laboratory",
    original_name: "Dexter's Laboratory",
    overview:
      "Dexter, a boy-genius with a secret laboratory, constantly battles his sister Dee Dee, who always gains access despite his best efforts to keep her out, as well as his arch-rival and neighbor, Mandark.",
    poster_path: "/inJJn8lUPWdvdy2h259UnoHWVqC.jpg",
    backdrop_path: "/yqKI437ohJAF9EQYkPYH0PTBDEt.jpg",
    vote_average: 7.658,
    vote_count: 832,
    first_air_date: "1996-04-28",
    genre_ids: [16, 35, 10765],
    origin_country: ["US"],
    original_language: "en",
    popularity: 95.072,
    adult: false,
  },
  {
    id: 604,
    name: "Teen Titans",
    original_name: "Teen Titans",
    overview:
      "Fighting for truth, justice and the last slice of pizza, these five superheroes are living proof you're never too young to save the planet. Protecting Earth and beyond, the Teen Titans use martial arts and gadgetry to battle villains.",
    poster_path: "/7DCq6XbJx5WGKPvSMBxYK9uJQWQ.jpg",
    backdrop_path: "/oIFxhR3nMmzZmj51gwifNR1whC4.jpg",
    vote_average: 8.367,
    vote_count: 1251,
    first_air_date: "2003-07-19",
    genre_ids: [16, 10759, 10765],
    origin_country: ["US"],
    original_language: "en",
    popularity: 21.1555,
    adult: false,
  },
  {
    id: 246,
    name: "Avatar: The Last Airbender",
    original_name: "Avatar: The Last Airbender",
    overview:
      "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.",
    poster_path: "/v2vn1coUMPKw0GI1KGC5J4IXtqp.jpg",
    backdrop_path: "/kU98MbVVgi72wzceyrEbClZmMFe.jpg",
    vote_average: 8.753,
    vote_count: 4417,
    first_air_date: "2005-02-21",
    genre_ids: [16, 10759, 10765],
    origin_country: ["US"],
    original_language: "en",
    popularity: 39.7283,
    adult: false,
  },
  {
    id: 888,
    name: "Spider-Man",
    original_name: "Spider-Man",
    overview:
      "Bitten by a neogenetic spider, Peter Parker develops spider-like superpowers. He uses these to fight crime while trying to balance it with the struggles of his personal life.",
    poster_path: "/peN9aqevr0edVoctVKGZDWFdTRl.jpg",
    backdrop_path: "/tszlsbfyTOPSZe2z6K4mwHtcnmI.jpg",
    vote_average: 8.289,
    vote_count: 1058,
    first_air_date: "1994-11-19",
    genre_ids: [16, 10759],
    origin_country: ["US"],
    original_language: "en",
    popularity: 57.6802,
    adult: false,
  },
  {
    id: 7842,
    name: "The Tom and Jerry Show",
    original_name: "The Tom and Jerry Show",
    overview:
      "The New Tom & Jerry Show is an animated television series produced for Saturday mornings by Hanna-Barbera Productions in association with Metro-Goldwyn-Mayer Television in 1975 for ABC based on the theatrical shorts and characters Tom and Jerry.",
    poster_path: "/qO0aveHUNqKciN9hO5EvBQGtZ3d.jpg",
    backdrop_path: "/sSPmVRgKLTerdyLVHxmF38DURUl.jpg",
    vote_average: 7.696,
    vote_count: 1143,
    first_air_date: "1975-09-06",
    genre_ids: [16, 10762, 10751, 35],
    origin_country: ["US"],
    original_language: "en",
    popularity: 16.3394,
    adult: false,
  },
  {
    id: 513,
    name: "Batman Beyond",
    original_name: "Batman Beyond",
    overview:
      "As new villains overrun Gotham City of the future, the aging Bruce Wayne hangs up the cape of the once invincible Batman. But when troubled teenager Terry McGinnis stumbles upon the Dark Knight's secret, a new alliance is forged. And a triumphant new Batman is born.",
    poster_path: "/1lgYfelvpinIMalYDt5rzudsFOH.jpg",
    backdrop_path: "/rbTGltRT79xGjbXH2CZTUgLHj4r.jpg",
    vote_average: 8.134,
    vote_count: 569,
    first_air_date: "1999-01-10",
    genre_ids: [16, 10759, 10765],
    origin_country: ["US"],
    original_language: "en",
    popularity: 33.5555,
    adult: false,
  },
  {
    id: 926,
    name: "Scooby-Doo, Where Are You!",
    original_name: "Scooby-Doo, Where Are You!",
    overview:
      "Fred, Daphne, Velma, Shaggy, and the talking dog, Scooby-Doo, travel on the Mystery Machine van, in search of weird mysteries to solve.",
    poster_path: "/lTzUSCtXR77CmGmEHcaxpxu2b4h.jpg",
    backdrop_path: "/m8xpVIsZlCVndlDxLrM8AUIg5GG.jpg",
    vote_average: 7.834,
    vote_count: 745,
    first_air_date: "1969-09-13",
    genre_ids: [16, 9648, 35, 10762, 10751],
    origin_country: ["US"],
    original_language: "en",
    popularity: 27.202,
    adult: false,
  },
  
];
